---
version: '3'
services:
  nginx:
    image: nginx
    depends_on:      
      - csserver
    hostname: nginx
    volumes:
     - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  csserver:
    hostname: csserver
    image: 
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
      - /volume1/dd/static_docker_volume:/static
    environment:
      CS_CLIENT_PORT: '8080'
      CS_SERVER_PORT: '3000'